name: Compilation

on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: clean local project
        run: dotnet clean
      - name: Build project
        run: |
          dotnet build
          7z a ./artifacts/bin.zip bin\
      - name: Publish Artifacts
        uses: actions/upload-artifact@v1        
        with:
          name: bin.zip
          path: ./artifacts/bin.zip
      