name: Build

on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: clean local project
        run: dotnet clean
      - name: Compilation
        run: |
          dotnet build -c Release
          7z a ./artifacts/Binaries.zip bin\
      - name: Publish compilation artifacts
        uses: actions/upload-artifact@v1        
        with:
          name: Binaries
          path: ./artifacts/Binaries.zip
      - name: Unit Tests
        run: dotnet test          
      