name: Unit Tests

on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: clean
        run: dotnet clean
      - name: Run unit Tests
        run: dotnet test